version: "3.9"

services:
  vpn-service:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - postgres
    command: /start
    networks:
      - vpn-network

  postgres:
    image: postgres:15-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres
    networks:
      - vpn-network
    platform: linux/amd64

  nginx:
    restart: always
    depends_on:
      - vpn-service
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - vpn-network
networks:
  vpn-network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres_data: {}
  postgres_data_backups: {}
